### ISSUE TITLE
iOS toolchain files still do not set ARM/AARCH64, leads to missing CPU_KNOWN_OPTIMIZATIONS

### ISSUE THREAD

**Issue by jdonald** [hunter-packages/opencv#28]
##### System information (version)

- OpenCV => 3.4.3-p2, various
- Operating System / Platform => macOS Mojave 10.14.1
- Compiler => Apple LLVM version 10.0.0 (clang-1000.11.45.5)

##### Detailed description

Despite the workaround in [this commit](https://github.com/ruslo/polly/commit/b6d9289043a0f2ec60b8b27a1aa229b96a349979), generally `CMAKE_SYSTEM_PROCESSOR` does not get set, which leads to both `AARCH64` and `ARM` never getting set, which leads to NEON not getting detected i.e.

```
--   CPU/HW features:
--     Baseline:
```

There's a good discussion on why CMAKE_SYSTEM_PROCESSOR needs to be set in ruslo/hunter#954 but it appears the workaround currently in polly is insufficient. OpenCVDetectCXXCompiler.cmake and OpenCVCompilerOptimizations.cmake depend on a value here in order to know to even run the checks for NEON (or SSE).

The problem is that the attempted fix:
```.cmake
set(_all_archs ${IPHONESIMULATOR_ARCHS} ${IPHONEOS_ARCHS})
list(LENGTH _all_archs _all_archs_len)
if(_all_archs_len EQUAL 1)
  set(CMAKE_SYSTEM_PROCESSOR ${_all_archs})
else()
  set(CMAKE_SYSTEM_PROCESSOR "")
endif()
```
doesn't work when _all_archs_len is greater than 1, which is the case when I use any ios-*.cmake, where _all_archs ends up being `x86_64;arm64` (simulator arch ; iPhone arch).

Note we are seeing NEON always properly detected with hunter targeting Android and this problem is specific to iOS.

##### Steps to reproduce

We run:
```sh
POLLY_IOS_DEVELOPMENT_TEAM="<our 10-digit ID>" POLLY_IOS_BUNDLE_IDENTIFIER="<our com.company.appname id>" \
  cmake -DCMAKE_TOOLCHAIN_FILE=~/polly/ios.cmake -G Xcode "<source dir>"
```
where the top-level CMake file does `hunter_add_package(OpenCV)`. When detecting CPU baseline features the output will just show `Baseline:` i.e. did not find NEON.

Compare that to the base case of grabbing non-hunter opencv's 3.4.3 tag and running:
```.sh
python platforms/ios/build_framework.py build/ios
```
Then the output will show successful detection of `Baseline: NEON` or `Baseline: NEON,FP16`.

**Comment by ruslo** [comment]
> Note we are seeing NEON always properly detected with hunter targeting Android and this problem is specific to iOS

Because Android is always single architecture build.

> python platforms/ios/build_framework.py build/ios

They are using different approach as far as I remember: run multiple builds with different toolchains. Hunter use single build with multiple architectures.

> doesn't work when _all_archs_len is greater than 1, which is the case when I use any ios-*.cmake, where _all_archs ends up being x86_64;arm64 (simulator arch ; iPhone arch).

Workaround is to use single architecture toolchain (I think you also can enable it explicitly by  ENABLE_NEON=ON?).

Nice solution would be to move enabling NEON optimization in C++ code and leave only something like `ENABLE_NEON_IF_AVAILABLE` to CMake:
* `ENABLE_NEON_IF_AVAILABLE=OFF` disable NEON optimization for all architectured unconditionally
* `ENABLE_NEON_IF_AVAILABLE=ON` (single ARM): check in C++ code that architecture is ARM and enable NEON optimization
* `ENABLE_NEON_IF_AVAILABLE=ON` (single AMD64): check in C++ code that architecture **is not** ARM and **disable** NEON optimization
* `ENABLE_NEON_IF_AVAILABLE=ON` (multi ARM + AMD64): C++ code will be compiled separately for each architecture: for ARM NEON optimization will be enabled and for AMD64 NEON optimization will be disabled

**Comment by ruslo** [comment]
Closing inactive discussion.

**Comment by jdonald** [comment]
Acknowledged. The proposals above would have been an improvement over the situation as it stands, but would have been substantial changes over how this is implemented across OpenCV today. As such we opted to continue limiting our Hunter builds to strictly single-architecture and doing a `lipo` on our final build products when iOS simulator (AMD64) compatibility was desired.

Developers may still experience the pitfall of a performance loss (OpenCV NEON optimizations removed) without a clear warning or error. Hopefully if they then search for terms such as OpenCV, NEON, iOS, and Hunter they'll find this closed ticket as useful documentation.
